services:
  - shelter
  - food
  - medical
  - hygiene
  - technology
  - legal
  - learning
  - overdose_prevention
  - phone
  - advocacy


welcomes:
  - male
  - female
  - transgender
  - children
  - youth
  - adult
  - senior


# default: &default
# adapter: postgresql
# encoding: unicode
# # For details on connection pooling, see Rails configuration guide
# # https://guides.rubyonrails.org/configuring.html#database-pooling
# pool: <%#= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# production
# <<: *default
# database: linkvan_api_production
# username: linkvan_api
# password: <%#= ENV['LINKVAN_API_DATABASE_PASSWORD'] %>
