name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: linkvan_api_test
          POSTGRES_USER: linkvan_api
          POSTGRES_PASSWORD: password
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@master

      - name: Setup Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Setup Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: |
          npm install -g npm
          sudo apt-get -yqq install libpq-dev
          gem install rails

      # Clean up git repo so the new rails template doesn't conflict
      - name: Remove git repo
        run: |
          rm -rf .git

      - name: Run tests
        env:
          TEST_APP_DATABASE_PASSWORD: password
        run: |
          rake
