name: Tests

on:
  pull_request:
    branches: '*'
  push:
    branches: [ master, develop ]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: linkvan_api
          POSTGRES_DB: linkvan_api_test
          POSTGRES_PASSWORD: password
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-rspec-${{ hashfiles('**/Gemfile.lock') }}
          restore-key: |
            ${{ runner.os }}-rspec-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle config set
          bundle install --jobs 4 --retry 3

      - name: Setup Node 15
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: JS package cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: linkvan_api
          run: |
            bin/rails db:setup

      - name: Run tests
        env:
        run: bin/rspec

      # - name: Install postgres client
        # run: sudo apt-get install libpq-dev
      # - name: Install dependencies
        # run: |
          # gem install bundler
          # bundler install
      # - name: Create database
        # run: |
          # bundler exec rails db:create RAILS_ENV=test
          # bundler exec rails db:migrate RAILS_ENV=test
      # - name: Run tests
        # run: bundler exec rake
      # - name: Upload coverage results    
        # uses: actions/upload-artifact@master
        # if: always()
        # with:
          # name: coverage-report
          # path: coverage

